#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

// 캐릭터 상태 및 액션 태그
namespace NCCharacter
{
	// 캐릭터 종류
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Walker);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Runner);

	// 이동 관련
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walk);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jog);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrouchSprint);

	// 상태 관련
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attacking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stand);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Landed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouch);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InventoryOpen);

	// 생존 관련
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Alive);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Downed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dead);
}

namespace NCItemType
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Consumable);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Material);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Currency);
}

namespace NCItemTag
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Armor);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Heal);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Credit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest);
}

namespace NCEquip
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hand_Left);
}

namespace NCLootBox
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_BeingLooted);
}

// 무기 관련 태그
namespace NCWeapon
{
	// 무기 타입
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Unarmed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_OneHanded);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_TwoHanded);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Pistol);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Shotgun);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Rifle);

	// 무기 무게
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weight_Light);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weight_Medium);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weight_Heavy);

	// 무기 액션
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Attacking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_SwingDelay);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Swapping);

	// 총기 / 조준 액션
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Aiming);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Firing);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Reloading);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_EmptyReloading);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Chambering);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_PumpAction);

	// 무기 상태
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Equipped);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Broken);
}

// 데미지 데이터 태그
namespace NCData
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
}

namespace NCGameStateTags
{
	// 게임 상태
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Title);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lobby);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameStart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameOver);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameClear);

	// 싱글, 멀티 여부
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SinglePlay);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MultiPlay);
};

// 총기 관련 태그
namespace NCGun
{
	// 총기 슬롯
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Primary);    // 주무기 (라이플/샷건)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Secondary);  // 보조무기 (권총/리볼버)

	// 총기 타입
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Rifle);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Shotgun);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Pistol);  // 권총/리볼버 통합

	// 발사 모드
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FireMode_Semi);   // 단발
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FireMode_Auto);   // 연사

	// 총기 액션
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Firing);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Reloading);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_ADS);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_ToggleFireMode);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Swapping); // 무기 교체 중 (입력 차단용)
}

namespace NCGunEffect
{
	// 이펙트 시작 위치
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gun_MuzzleFlash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gun_ShellEject);
	
	// 총알 궤적
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gun_Tracer);
	
	// 힛 이펙트
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gun_Impact);
}

namespace NCMeleeEffect
{
	// 힛 이펙트
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Melee_Hit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Melee_Surface);
}
